### ISSUE TITLE
Using rust-bindgen as a build dependency

### ISSUE THREAD

**Issue by viniciusd** [oxfordcontrol/osqp.rs#11]
Hi, thanks and congrats for the great work you put here.

I worked throughout this week in OSQP bindings for rust and just found out you have already done both bindings and wrappers.

Something that caught my attention is the fact you are using bindgen's CLI in order to automatically generated the bindings. Therefore, it assumes bindgen is already installed in the build machine. Have you considered adding rust-bindgen to the build dependencies and integrating that to the build.rs file instead? This way, cargo would already take care of installing rust-bindgen to the machine.

I would like to hear your thoughts on that. If you agree, I can take this task and submit a pull request.

**Comment by ebarnard** [comment]
Hi,

At the moment the bindings are pregenerated and checked in [here](https://github.com/oxfordcontrol/osqp.rs/blob/master/osqp-sys/src/bindings.rs) every time osqp-sys is updated to a new release of the OSQP C library. Therefore only people developing the osqp-sys crate need to install the bindgen CLI (which isn't very many people). Users of the osqp or osqp-sys crates do not which saves three minutes of build time vs using bindgen as a dev-dependency on my machine.

It would be interesting to include bindgen as a dev-dependency for osqp-sys where it can automatically check, when working on osqp-sys, whether the pregenerated bindings are correct but I don't know whether that is possible.

**Comment by viniciusd** [comment]
I'd started an osqp-sys project before noting your binds were already available. My approach there was running bindgen from the build.rs script:  https://github.com/viniciusd/cvxrs/blob/master/osqp-sys/build.rs

Then bindgen becomes a mere build dependency at Cargo.toml:
```
[build-dependencies]
bindgen = "0.51.1"
```

**Comment by ebarnard** [comment]
I'm keen not to significantly increase the initial compile time of `osqp-sys` and by extension `osqp`. Which adding bindgen as a dependency will do.

I notice in https://github.com/viniciusd/cvxrs/blob/master/osqp-sys/build.rs you generate bindings from a locally installed copy of osqp. Do you have a use case that is not covered by the existing approach of pre-generating the bindings and having cargo compile an embedded copy of the OSQP C library?

**Comment by ebarnard** [comment]
I should mention that at present the OSQP C library does not promise a stable API or ABI which is why I do not currently support linking against a locally installed copy of the OSQP C library.

**Comment by viniciusd** [comment]
Nope, it is not about some uncovered case.
I simply decided to start checking automatic bind generation before checking about the I build process in the `build.rs` file. It would be my next step if I hadn't found your repository.

**Comment by ebarnard** [comment]
Ah, fair enough. Bindgen is an amazing tool, but not the right fit for this project.

**Comment by viniciusd** [comment]
Aren't you using exactly bindgen or did I get something wrong here?
https://github.com/oxfordcontrol/osqp.rs/blob/master/osqp-sys/generate_bindings.sh
The only difference would be moving this to the `build.rs` file instead of using a shell script

**Comment by ebarnard** [comment]
There is a big difference between that shell script and using bindgen from a `build.rs` file.

When using the shell script, users of osqp or osqp-sys do not have to use or build bindgen.

When using a `build.rs` script cargo will build a copy of bindgen whenever osqp or osqp-sys is used. This is something I do not want.
